# Generated by Django 2.2.2 on 2019-07-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infPro', '0002_auto_20190701_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinformation',
            name='Application_Owner',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='projectinformation',
            name='Application_Server_IP',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='projectinformation',
            name='Application_Server_Name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='projectinformation',
            name='Database_Name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='projectinformation',
            name='Database_Server_IP',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='projectinformation',
            name='Database_Server_Name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='projectinformation',
            name='Database_Version',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='projectinformation',
            name='Server_OS_Version',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='projectinformation',
            name='Support_Team_Group_Name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
