# Generated by Django 2.2.2 on 2019-07-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Application_Owner', models.TextField(blank=True)),
                ('Support_Team_Group_Name', models.TextField(blank=True)),
                ('Application_Server_Name', models.TextField(blank=True)),
                ('Application_Server_IP', models.TextField(blank=True)),
                ('Server_OS_Version', models.TextField(blank=True)),
                ('Database_Server_Name', models.TextField(blank=True)),
                ('Database_Server_IP', models.TextField(blank=True)),
                ('Database_Name', models.TextField(blank=True)),
                ('Database_Version', models.TextField(blank=True)),
            ],
        ),
    ]
