# Generated by Django 2.2.2 on 2019-07-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infPro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinformation',
            name='Application_Owner',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectinformation',
            name='Application_Server_IP',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectinformation',
            name='Application_Server_Name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectinformation',
            name='Database_Name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectinformation',
            name='Database_Server_IP',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectinformation',
            name='Database_Server_Name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectinformation',
            name='Database_Version',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectinformation',
            name='Server_OS_Version',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectinformation',
            name='Support_Team_Group_Name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
